version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
   
    commands:
      - echo "Installing custom Node.js version 16 ..."
      - |
        curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash - && \
        sudo yum install -y nodejs
      - echo "Installing npm packages ..."
      - npm install
       
  build:
    commands:
      - echo "Running build script ..."
      - npm run-script build
     
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - server.js
    - appspec.yml
    - scripts/**/*
