version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Navigating to react-frontend directory..."
      - cd react-frontend
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the React app..."
      - npm run build
  post_build:
    commands:
      - echo "Post-build steps..."

artifacts:
  files:
    - '**/*'
  base-directory: react-frontend/build
